name: NAMC-Fish
version: '${project.version}'
main: pershkin.perspvefishing.PersPvEFishing
api-version: '1.16'
softdepend: [Vault]

commands:
  fish:
    description: Main NAMC-Fish command
    usage: /fish <sell|give|stats|top|reload>

permissions:
  fishing.use:
    description: Allows players to use NAMC-Fish features
    default: true
  fishing.sell:
    description: Allows selling custom fish
    default: true
  fishing.admin:
    description: Admin access for NAMC-Fish commands
    default: op
